### ISSUE TITLE
Bug when trying to swipe message

### ISSUE THREAD

**Issue by ridik1803** [nventive/Binding.Intercom#7] opened 2018-09-28 08:05 UTC
When I'm trying to swipe more then one message from list above my app, messages stop swipping and freeze up

**Comment by GuillaumeSE** [comment] 2021-02-12 16:10
Hello
Sorry for the late reply.  Can you try the latest version available.
I'm closing the issue issue in the meantime

**Closed by GuillaumeSE** 2021-02-12 16:10 UTC
